document.addEventListener("DOMContentLoaded", function () {
    console.log("JavaScript loaded and executing...");

    // Select the headline element
    const headlineElement = document.getElementById("headline");

    // Ensure the headline element exists
    if (!headlineElement) {
        console.error("Error: 'headline' element not found in HTML.");
        return;
    }

    // Array of Scottish football clubs
    const clubs = [
     "Celtic", "Rangers", "Aberdeen", "Hearts", "Hibs", "Dundee United", "Motherwell", "Livingston", "Kilmarnock", "Ross County", "St Mirren", "St Johnstone",
     "Dunfermline Athletic", "Ayr United", "Falkirk", "Queen’s Park", "Partick Thistle", "Greenock Morton", "Inverness Caledonian Thistle", "Raith Rovers", "Hamilton Accies", "Dundee", "Arbroath",
     "Clyde", "Queen of the South", "Montrose", "Forfar Athletic", "East Fife", "Airdrieonians", "Alloa Athletic", "Edinburgh City", "Kelty Hearts", "Stirling Albion",
     "Elgin City", "Annan Athletic", "Stranraer", "Albion Rovers", "Peterhead", "Brechin City", "Cowdenbeath", "Cove Rangers", "Gala Fairydean Rovers", "Spartans",
     "Brora Rangers", "Buckie Thistle", "Clachnacuddin", "Deveronvale", "Formartine United", "Forres Mechanics", "Fraserburgh", "Huntly", "Inverurie Loco Works", "Keith", "Lossiemouth", "Nairn County", "Rothes", "Strathspey Thistle", "Turriff United",
     "Berwick Rangers", "Bonnyrigg Rose", "Broomhill", "Caledonian Braves", "Celtic B", "Civil Service Strollers", "Cowdenbeath", "Cumbernauld Colts", "Dalbeattie Star", "East Kilbride","Edinburgh University", "Gretna 2008", "Hearts B", "University of Stirling", "Rangers B"
    ];

    // Array of Red Top style headlines
    const headlines = [
        "ROCKED BY SHOCK SCANDAL",
        "AT THE CENTRE OF TRANSFER STORM",
        "HUMILIATED IN CHAOTIC CLASH",
        "FANS IN MELTDOWN OVER BOMBSHELL ANNOUNCEMENT",
        "BOSS UNDER FIRE AS TEAM CRISIS DEEPENS",
        "SET FOR BLOCKBUSTER CASH SPLASH IN TRANSFER WINDOW",
        "HIT BY MAJOR CONTROVERSY AS FOOTBALL AUTHORITIES STEP IN",
        "IN SHAMBLES AFTER LAST-MINUTE COLLAPSE",
        "LEFT RED-FACED AFTER SOCIAL MEDIA BLUNDER",
        "FACING LEGAL BATTLE OVER DISPUTED TRANSFER FEE",
        "STADIUM PLANS IN RUINS AFTER FUNDING COLLAPSE",
        "HIT WITH SHOCK POINTS DEDUCTION",
        "BLOCKED FROM EUROPEAN COMPETITION OVER LICENSING ISSUES",
        "FANS THREATEN BOYCOTT AFTER TICKET PRICE HIKE",
        "FLOPS IN PRE-SEASON FRIENDLY AGAINST MINNOWS"
        "ROCKED BY SHOCK SCANDAL INVOLVING MYSTERIOUS 'GHOST PLAYER'",
        "HUMILIATED AS TEAM FORGETS TO BRING MATCH KITS - PLAYS IN TRAINING BIBS",
        "FANS IN MELTDOWN AFTER CLUB ANNOUNCES NEW SPONSORSHIP DEAL WITH LOCAL CHIP SHOP",
        "BOSS UNDER FIRE AFTER SECRETLY USING FOOTBALL MANAGER TO PLAN TACTICS",
        "STADIUM CHAOS AS GROUNDSKEEPER PAINTS PENALTY SPOT IN WRONG PLACE",
        "HIT BY CONTROVERSY AS REFEREE CAUGHT CHECKING BETTING ODDS MID-GAME",
        "EMBARRASSING MOMENT AS CLUB ANNOUNCES SIGNING OF A PLAYER WHO DOESN’T EXIST",
        "DEFENDS DECISION TO HIRE MANAGER WITH 0% WIN RECORD - 'HE HAS GOOD ENERGY'",
        "FORCED TO ISSUE APOLOGY AFTER STADIUM PA SYSTEM ACCIDENTALLY PLAYS RIVAL TEAM'S ANTHEM",
        "SET TO LAUNCH 'REVOLUTIONARY' NEW TACTIC INSPIRED BY SUNDAY LEAGUE FOOTBALL",
        "FACING FINANCIAL CRISIS AFTER SPENDING ENTIRE TRANSFER BUDGET ON NEW TOILET SEATS",
        "ANNOUNCES NEW BADGE DESIGN - FANS SAY IT LOOKS LIKE A PACKET OF BISCUITS",
        "MATCH DELAYED AFTER MANAGER LOCKS HIMSELF IN DRESSING ROOM TO 'GATHER HIS THOUGHTS'",
        "BIZARRE NEW FITNESS REGIME SEES PLAYERS TRAIN WITH LOCAL LINE DANCING GROUP",
        "DEFENDER SENT OFF AFTER CELEBRATING TOO EARLY - BALL NEVER CROSSED LINE",
        "STUNS FANS BY DECLARING THEIR MATCH-WINNING GOAL AS 'AN ACCIDENT'",
        "PRE-SEASON FRIENDLY DESCENDS INTO CHAOS AS BOTH TEAMS TURN UP IN IDENTICAL KITS",
        "TEAM ACCIDENTALLY ANNOUNCES NEW SIGNING - WHO RETIRED IN 2004",
        "MANAGER HOLDS CRISIS TALKS AFTER TEAM RECORDS RECORD LOW POSSESSION: 1%",
        "APPOINTS NEW MANAGER - WHO CLAIMS HE 'DOESN'T REALLY FOLLOW FOOTBALL'",
        "TEAM UNVEILS CONTROVERSIAL NEW CLUB MASCOT THAT TERRIFIES CHILDREN",
        "CLUB REBRANDS AS 'THE REAL GIANTS OF SCOTTISH FOOTBALL' - CURRENTLY 10TH IN LEAGUE",
        "NEW SIGNING PRAISES THE CLUB - THEN ADMITS HE ACTUALLY MEANT THEIR RIVALS",
        "MATCH POSTPONED AFTER TEAM BUS DRIVER GETS LOST ON WAY TO STADIUM",
        "FAN OUTRAGE AS TEAM RELEASES 'REVOLUTIONARY' NEW KIT THAT'S JUST A WHITE T-SHIRT",
        "TEAM CHAIRMAN DECLARES CLUB 'BIGGER THAN BARCELONA' - CURRENTLY FIGHTING RELEGATION",
        "MATCHBALL MYSTERIOUSLY DEFLATES MID-GAME - SPARKS INVESTIGATION",
        "PLAYER REFUSES TO PLAY AFTER SEEING OPPOSITION MANAGER 'GIVE HIM A FUNNY LOOK'"
        "FACING BACKLASH AFTER SIGNING PLAYER WHO RETIRED 15 YEARS AGO",
        "SET TO LAUNCH REVOLUTIONARY 'NO DEFENDERS' FORMATION AFTER CONCEDING 6 GOALS",
        "FACING INVESTIGATION AFTER OPPOSITION'S GOAL NET IS DISCOVERED TO BE TOO SMALL",
        "FANS HORRIFIED AS CLUB'S NEW BADGE LOOKS LIKE A SCHOOL LOGO FROM 1994",
        "SET TO INTRODUCE CONTROVERSIAL ‘HALF-TIME LOTTERY’ FOR SECOND-HALF STARTING XI",
        "DEFENDS DECISION TO SIGN PLAYER BASED PURELY ON HIS FIFA RATING",
        "HITS FINANCIAL TURMOIL AFTER CHAIRMAN BETS ENTIRE BUDGET ON HORSE RACING",
        "ISSUES APOLOGY AFTER RELEASING LIMITED-EDITION KIT WITH MASSIVE SPELLING ERROR",
        "BOSS REFUSES TO RESIGN – CLAIMS 'IT COULD BE WORSE' WHILE 12TH IN LEAGUE",
        "HITS ROCK BOTTOM AFTER FAN IS ASKED TO PLAY INJURY-TIME DUE TO LACK OF SUBS",
        "FANS LEFT STUNNED AS TEAM'S TIKI-TAKA STYLE RESULTS IN OWN GOAL FROM 50 YARDS",
        "CHAOS AS CLUB'S NEW SIGNING REFUSES TO PLAY AFTER REALISING IT’S COLD IN SCOTLAND",
        "EMBARRASSMENT AS TEAM CELEBRATES WIN ONLY TO REALISE IT WAS A DRAW",
        "ANNOUNCES RECORD-BREAKING SEASON TICKET SALES - FORGETS TO ORDER ENOUGH SEATS",
        "STUNS FANS WITH PROMISE OF ‘TOTAL FOOTBALL’ – LOSES NEXT GAME 7-0",
        "BACKLASH AS NEW CLUB ANNOUNCEMENT TURNS OUT TO BE A SALE ON MUGS IN THE GIFT SHOP"
        "CHAIRMAN ADMITS HE ONLY BOUGHT THE CLUB TO ‘GET FREE PIES AT HALFTIME’",
        "STUNS FOOTBALL WORLD BY HIRING AN AI ROBOT AS HEAD COACH – IT’S ALREADY RESIGNED",
        "CLUB SHOP SELLING MYSTERIOUSLY SHRINKING HOME SHIRTS – BLAMES ‘GLOBAL WARMING’",
        "SACKS MANAGER AFTER JUST 45 MINUTES IN CHARGE – BLAMES ‘BAD VIBES’",
        "MATCH DELAYED AFTER BALL BURSTS ON FIRST KICK – NO SPARE AVAILABLE",
        "FANS DEMAND REFUND AFTER 0-0 DRAW CONTAINS EXACTLY ZERO SHOTS ON TARGET",
        "SPARKS CONTROVERSY AFTER PLAYING CHRISTMAS MUSIC AT A MATCH IN AUGUST",
        "SUPPORTERS GROUP THREATENS PROTEST AFTER CLUB REBRANDS AS ‘THE PRIDE OF SCOTTISH FOOTBALL’ – CURRENTLY 11TH",
        "CONFIRMS NEW STRIKER – HASN’T SCORED A GOAL SINCE 2016",
        "BOSS EXPLAINS RECENT LOSING STREAK – CLAIMS ‘WE’RE JUST UNLUCKY, EVERY WEEK’",
        "MASCOT CONTROVERSY AFTER NEW DESIGN IS ‘TOO TERRIFYING FOR CHILDREN’",
    ];

    // Array of dramatic endings
    const endings = [
        "AS RIVAL FANS MOCK IN BRUTAL TROLLING",
        "AND PUNDITS SAY 'IT'S A TOTAL DISGRACE!'",
        "AS FURIOUS SUPPORTERS DEMAND ANSWERS",
        "LEAVING MANAGER CLUELESS ON HOW TO RESPOND",
        "WITH EMERGENCY MEETING NOW UNDERWAY",
        "FORCING CLUB LEGENDS TO SPEAK OUT",
        "SPARKING WILD CELEBRATIONS AMONG OPPOSITION SUPPORTERS",
        "WITH FURTHER REVELATIONS EXPECTED IN THE COMING DAYS",
        "LEAVING FANS ABSOLUTELY OUTRAGED",
        "AND TV PUNDITS CALL IT ‘A NATIONAL EMBARRASSMENT’"
        "AS RIVAL FANS MOCK IN BRUTAL TROLLING - EVEN THEIR OWN FANS JOIN IN",
        "AND PUNDITS CALL IT 'A DISGRACE TO FOOTBALL'",
        "AS FURIOUS SUPPORTERS DEMAND THE CLUB BE RELEGATED FOR EMBARRASSMENT",
        "LEAVING MANAGER CLUELESS ON HOW TO RESPOND - SAYS 'I'M JUST AS CONFUSED AS YOU ARE'",
        "WITH EMERGENCY BOARD MEETING NOW UNDERWAY - COULD SPELL DISASTER",
        "FORCING CLUB LEGENDS TO SPEAK OUT - 'WE NEVER SAW ANYTHING THIS BAD IN OUR DAY'",
        "SPARKING WILD CELEBRATIONS FROM OPPOSITION SUPPORTERS - EVEN NEUTRALS FIND IT FUNNY",
        "WITH FURTHER REVELATIONS EXPECTED IN THE COMING DAYS - COULD GET WORSE",
        "LEAVING FANS ABSOLUTELY OUTRAGED - BUT STILL RENEWING SEASON TICKETS",
        "AND TV PUNDITS CALL IT 'A NATIONAL EMBARRASSMENT' - WORSE THAN THE 1978 WORLD CUP",
        "PROMPTING FANS TO START A PETITION TO 'DELETE THE CLUB'",
        "AS LOCAL NEWSPAPER LABELS THEM 'THE LAUGHING STOCK OF SCOTLAND'",
        "RESULTING IN ANGRY SUPPORTERS ORGANIZING A 'PROTEST MARCH' WITH ONLY 3 ATTENDEES",
        "WITH RIVAL CLUBS NOW OPENLY LAUGHING AT THEM ON SOCIAL MEDIA",
        "CAUSING SPONSORS TO PULL OUT - REPLACED BY LOCAL PET SHOP",
        "AS CLUB MANAGER REFUSES TO ANSWER QUESTIONS - SAYS HE'S 'GONE FOR A LONG WALK'",
        "LEAVING FANS ASKING 'HOW MUCH WORSE CAN THIS GET?'",
        "FORCING PLAYERS TO APOLOGIZE PUBLICLY - ONE JUST SHRUGS AND WALKS OFF",
        "LEADING TO URGENT CALLS FOR 'A FULL REBUILD' - DESPITE NO MONEY LEFT",
        "WITH ANGRY PUNDITS CALLING FOR GOVERNMENT INTERVENTION",
        "AS EVEN RIVAL CLUBS OFFER SYMPATHY - 'NOBODY DESERVES THIS'"
        "WITH PUNDITS CALLING IT 'THE WORST DECISION SINCE THE INVENTION OF THE OFFSIDE RULE'",
        "SPARKING NATIONAL DEBATE OVER WHETHER FOOTBALL SHOULD JUST BE ABOLISHED",
        "FORCING CLUB CHAIRMAN TO DELETE TWITTER IN SHAME",
        "PROMPTING PANIC AS EVEN THE MASCOT STARTS QUESTIONING HIS ROLE AT THE CLUB",
        "WITH CLUB OFFICIALS SCRAMBLING TO FIND EXCUSES",
        "LEAVING SUPPORTERS ASKING 'HOW MUCH LOWER CAN WE GO?'",
        "RESULTING IN ANGRY SUPPORTERS ORGANIZING A PETITION TO ‘BRING BACK COMMON SENSE’",
        "SPARKING A RIOT IN THE CLUB'S OFFICIAL FAN FORUM",
        "FORCING PLAYERS TO APOLOGIZE BY WRITING A LETTER TO EVERY FAN INDIVIDUALLY",
        "LEAVING THE MANAGER STARING INTO THE DISTANCE, WONDERING IF THIS IS ALL WORTH IT",
        "FORCING CLUB CHAIRMAN TO GO INTO HIDING – POSSIBLY IN THE LOCAL PUB",
        "LEAVING FOOTBALL EXPERTS BAFFLED – EVEN BY SCOTTISH FOOTBALL STANDARDS",
        "FORCING FANS TO LAUNCH A FUNDRAISER JUST TO BUY A DECENT STRIKER",
        "LEAVING LONG-TERM SEASON TICKET HOLDERS WONDERING WHY THEY STILL BOTHER",
        "LEADING TO NATIONAL SHAME AS EVEN ENGLISH CLUBS START TAKING THE MICK",
    ];

    // Function to generate a random headline
    function generateHeadline() {
        const club = clubs[Math.floor(Math.random() * clubs.length)];
        const headline = headlines[Math.floor(Math.random() * headlines.length)];
        const ending = endings[Math.floor(Math.random() * endings.length)];

        headlineElement.innerText = `${club} ${headline} ${ending}`;
    }

    // Generate and insert headline immediately on page load
    generateHeadline();
});
