// Arrays of Scottish football-related terms
const subjects = [
    "CELTIC", "RANGERS", "ABERDEEN", "HEARTS", "HIBS", "DUNDEE", "DUNDEE UNITED", "MOTHERWELL", "LIVINGSTON",
    "KILMARNOCK", "ROSS COUNTY", "ST MIRREN", "ST JOHNSTONE"
];

const headlines = [
    "ROCKED BY SHOCK SCANDAL",
    "AT THE CENTRE OF TRANSFER STORM",
    "HUMILIATED IN CHAOTIC CLASH",
    "FANS IN MELTDOWN OVER BOMBSHELL ANNOUNCEMENT",
    "BOSS UNDER FIRE AS TEAM CRISIS DEEPENS",
    "SET FOR BLOCKBUSTER CASH SPLASH IN TRANSFER WINDOW",
    "HIT BY MAJOR CONTROVERSY AS FOOTBALL AUTHORITIES STEP IN",
    "RIPPED APART BY FORMER MANAGER IN BRUTAL VERDICT",
    "IN SHAMBLES AFTER LAST-MINUTE COLLAPSE",
    "LEFT RED-FACED AFTER SOCIAL MEDIA BLUNDER",
    "SET TO AXE STAR IN SHOCK U-TURN",
    "BIZARRE TACTICS LEAVE PUNDITS IN STITCHES",
    "BOARD SLAMS TEAM AS 'WORST PERFORMANCE EVER SEEN'",
    "STUNS FANS WITH UNBELIEVABLE ANNOUNCEMENT",
    "UNDER INVESTIGATION AFTER ALLEGATIONS EMERGE",
    "FACING LEGAL BATTLE OVER DISPUTED TRANSFER FEE",
    "FANS DEMAND ANSWERS OVER MISSING FUNDS",
    "PLOTTING MASSIVE REBUILD AFTER DISASTROUS SEASON",
    "ACCUSATIONS FLY OVER UNFAIR REFEREEING DECISION",
    "BOSSES IN CHAOS AS MANAGERIAL SEARCH DRAGS ON",
    "FORCED TO PLAY BEHIND CLOSED DOORS AFTER FAN INCIDENT",
    "STADIUM PLANS IN RUINS AFTER FUNDING COLLAPSE",
    "HIT WITH SHOCK POINTS DEDUCTION",
    "FACING FINANCIAL MELTDOWN AFTER FAILED INVESTMENT",
    "BLOCKED FROM EUROPEAN COMPETITION OVER LICENSING ISSUES",
    "REVEALS BOLD NEW LOGO - FANS AREN'T HAPPY",
    "LAUNCHES CONTROVERSIAL NEW SPONSORSHIP DEAL",
    "BIZARRE MATCHDAY PROMOTION LEAVES SUPPORTERS FURIOUS",
    "FANS THREATEN BOYCOTT AFTER TICKET PRICE HIKE",
    "SET TO UNVEIL SURPRISE STADIUM NAME CHANGE",
    "BACKLASH ERUPTS OVER NEW HOME KIT DESIGN",
    "SLAMMED FOR 'DISGRACEFUL' PERFORMANCE IN LOCAL DERBY",
    "DEFENDS DECISION TO SACK MANAGER MID-SEASON",
    "HITS RECORD LOW ATTENDANCE AFTER DISMAL START",
    "CRITICISED FOR 'EMBARRASSING' SOCIAL MEDIA CAMPAIGN",
    "HUMILIATED BY LOWEST-RANKED OPPOSITION IN CLUB HISTORY",
    "SET TO SCRAP WOMEN’S TEAM AMIDST FUNDING CUTS",
    "DROPS OUT OF CUP COMPETITION AFTER FIELDING INELIGIBLE PLAYER",
    "FACING MAJOR UEFA SANCTIONS AFTER FAN TROUBLE",
    "ACCUSATIONS OF ‘DIRTY MONEY’ ROCK CLUB BOARDROOM",
    "SENDS SCOUTS TO NON-LEAGUE MATCH IN DESPERATE MOVE",
    "FAN GROUPS DEMAND MEETING WITH CLUB HIERARCHY",
    "FLOPS IN PRE-SEASON FRIENDLY AGAINST MINNOWS",
    "ACCIDENTALLY LEAKS NEW SIGNING BEFORE OFFICIAL ANNOUNCEMENT",
    "BOARDROOM POWER STRUGGLE THREATENS CLUB’S FUTURE",
    "PUNDITS LEFT STUNNED BY BIZARRE FORMATION CHANGE",
    "HITS NEW LOW IN HISTORIC LOSING STREAK",
    "SET TO OFFER MANAGER HUGE NEW CONTRACT DESPITE FAN ANGER",
    "FORCED TO CANCEL MATCH AFTER PITCH DISASTER",
    "BANNED FROM COMPETITION AFTER MAJOR RULE BREACH",
    "STUNS FANS WITH SURPRISE STADIUM RELOCATION PLANS",
    "REFUSES TO COMMENT ON SHOCK TAKEOVER RUMOURS",
    "CRISIS TALKS UNDERWAY AFTER EMBARRASSING DEFEAT",
    "FACES EMBARRASSING LAWSUIT FROM SPONSOR OVER CONTRACT BREACH"
];

const endings = [
    "AS RIVAL FANS MOCK IN BRUTAL TROLLING",
    "AND PUNDITS SAY 'IT'S A TOTAL DISGRACE!'",
    "AS FURIOUS SUPPORTERS DEMAND ANSWERS",
    "IN A TWIST THAT NOBODY SAW COMING",
    "LEAVING BOSS FACING THE SACK",
    "WITH LEGENDARY EX-MANAGER ‘LINING UP RETURN’",
    "AS CHAOS ERUPTS BEHIND THE SCENES",
    "WITH CLUB FUTURE NOW IN SERIOUS DOUBT",
    "AS FANS CALL IT ‘THE WORST NEWS EVER’",
    "IN SHOCKING SCENES THAT STUNNED EVERYONE",
    "LEAVING FOOTBALL WORLD COMPLETELY BAFFLED",
    "AS ANGRY BOARD MEMBERS CONFRONT MANAGER",
    "AND EVEN THE PLAYERS CAN’T BELIEVE IT",
    "AS PANIC SETS IN AHEAD OF CRUNCH FIXTURE",
    "WITH MASSIVE FALLOUT EXPECTED IN COMING DAYS",
    "AS FURIOUS CHAIRMAN HOLDS EMERGENCY MEETING",
    "PROMPTING MASS WALKOUT FROM SEASON TICKET HOLDERS",
    "AS LEGAL ACTION NOW LOOKS INEVITABLE",
    "WITH RIVAL CLUBS SET TO LODGE FORMAL COMPLAINT",
    "FORCING FANS TO PROTEST OUTSIDE STADIUM",
    "SPARKING WILD CELEBRATIONS AMONG OPPOSITION SUPPORTERS",
    "AS RIVAL TEAM HILARIOUSLY TROLLS THEM ON TWITTER",
    "WITH FORMER BOSS LABELING CLUB A ‘JOKE’",
    "LEAVING MANAGER CLUELESS ON HOW TO RESPOND",
    "AND NOW UEFA THREATENS MAJOR SANCTIONS",
    "IN BIZARRE TURN OF EVENTS THAT DEFIES LOGIC",
    "AS PUNDITS LABEL IT ‘THE WORST DECISION IN YEARS’",
    "WITH PLAYERS NOW THREATENING TO STRIKE",
    "CAUSING MASSIVE FALL-OUT ACROSS SCOTTISH FOOTBALL",
    "AS FOOTBALL AUTHORITIES OPEN FORMAL INVESTIGATION",
    "WITH REPORTS SUGGESTING SECRET TALKS WITH RIVAL CLUB",
    "WITH FANS LEFT 'ABSOLUTELY SICKENED' BY THE NEWS",
    "FORCING CHAIRMAN TO BREAK SILENCE IN RARE INTERVIEW",
    "AND CLUB LEGENDS LEFT HORRIFIED BY DECISION",
    "AS TV PUNDIT CALLS IT ‘A NATIONAL EMBARRASSMENT’",
    "LEAVING LONG-TERM SPONSORS ‘DEEPLY CONCERNED’",
    "WITH FURTHER REVELATIONS EXPECTED IN THE COMING DAYS"

// Function to generate a random headline
function generateHeadline() {
    const club = clubs[Math.floor(Math.random() * clubs.length)];
    const headline = headlines[Math.floor(Math.random() * headlines.length)];
    const ending = endings[Math.floor(Math.random() * endings.length)];

    document.getElementById("headline").innerText = `${club} ${headline} ${ending}`;
}

// Add event listener for button click
document.getElementById("generateButton").addEventListener("click", generateHeadline);

// Generate a headline when the page loads
window.onload = generateHeadline;
